name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - name: rustfmt
      if: ${{ !cancelled() }}
      run: cargo fmt -- --check
    - name: clippy
      if: ${{ !cancelled() }}
      run: cargo clippy --all-features -- -D warnings
    - name: build
      if: ${{ !cancelled() }}
      run: cargo build --verbose --all-features --all-targets --tests --examples
    - name: test
      if: ${{ !cancelled() }}
      run: cargo test --verbose --all-features --all-targets

    - name: run js scripts tests
      if: ${{ !cancelled() }}
      run: |
        cargo run --example js -- js-scripts/async_n_throw_async_tests.js
        cargo run --example js -- js-scripts/atomics_test.js
        cargo run --example js -- js-scripts/atomics_wait_notify_test.js
        cargo run --example js -- js-scripts/boxed_types_tests.js
        cargo run --example js -- js-scripts/check_dataview_global.js
        cargo run --example js -- js-scripts/comprehensive_dataview_test.js
        cargo run --example js -- js-scripts/dataview_properties_test.js
        cargo run --example js -- js-scripts/date_tests.js
        cargo run --example js -- js-scripts/date_utc_n_get_time_zone_offset.js
        cargo run --example js -- js-scripts/function_object.js
        cargo run --example js -- js-scripts/globel_assert.js
        cargo run --example js -- js-scripts/object_super_method_stack_overflow.js
        cargo run --example js -- js-scripts/object_teats.js
        cargo run --example js -- js-scripts/parameter_rest.js
        cargo run --example js -- js-scripts/proper_dataview_test.js
        cargo run --example js -- js-scripts/regex_test_2.js
        cargo run --example js -- js-scripts/regex_test_3.js
        cargo run --example js -- js-scripts/regex_test.js
        cargo run --example js -- js-scripts/sharedarraybuffer_test.js
        cargo run --example js -- js-scripts/simple_dataview_test.js
        cargo run --example js -- js-scripts/template_string_tests_2.js
        cargo run --example js -- js-scripts/template_string_tests.js
        cargo run --example js -- js-scripts/test_array_join_split.js
        cargo run --example js -- js-scripts/test_dataview_js.js
        cargo run --example js -- js-scripts/test_typedarray_constructors.js
        cargo run --example js -- js-scripts/try_catch_finally.js
        cargo run --example js -- js-scripts/typeof_n_callable.js

    - name: Abort on error
      if: ${{ failure() }}
      run: echo "Some of jobs failed" && false
