name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - name: rustfmt
      if: ${{ !cancelled() }}
      run: cargo fmt -- --check
    - name: clippy
      if: ${{ !cancelled() }}
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: build
      if: ${{ !cancelled() }}
      run: cargo build --verbose --all-features --all-targets --tests --examples
    - name: test
      if: ${{ !cancelled() }}
      run: |
        cargo test --verbose --all-features
        cargo test --verbose

    - name: run js scripts tests
      if: ${{ !cancelled() }}
      run: |
        # cargo run --all-features --example js -- js-scripts/async_n_throw_async_tests.js
        cargo run --all-features --example js -- js-scripts/atomics_test.js
        cargo run --all-features --example js -- js-scripts/atomics_wait_notify_test.js
        cargo run --all-features --example js -- js-scripts/bigint_test.js
        cargo run --all-features --example js -- js-scripts/boxed_types_tests.js
        cargo run --all-features --example js -- js-scripts/check_dataview_global.js
        cargo run --all-features --example js -- js-scripts/classes_usage.js
        cargo run --all-features --example js -- js-scripts/comprehensive_dataview_test.js
        cargo run --all-features --example js -- js-scripts/dataview_properties_test.js
        cargo run --all-features --example js -- js-scripts/date_tests.js
        cargo run --all-features --example js -- js-scripts/date_utc_n_get_time_zone_offset.js
        cargo run --all-features --example js -- js-scripts/destructuring_assignments.js
        cargo run --all-features --example js -- js-scripts/es6_module_test_01.js
        cargo run --all-features --example js -- js-scripts/es6_module_test_02.js
        cargo run --all-features --example js -- js-scripts/es6_module_test_03.js
        cargo run --all-features --example js -- js-scripts/expressions_n_operators.js
        cargo run --all-features --example js -- js-scripts/function_object.js
        cargo run --all-features --example js -- js-scripts/globel_assert.js
        cargo run --all-features --example js -- js-scripts/indexed_collections.js
        cargo run --all-features --example js -- js-scripts/json_tests.js
        cargo run --all-features --example js -- js-scripts/keyed_collections.js
        cargo run --all-features --example js -- js-scripts/loops_n_iteration.js
        cargo run --all-features --example js -- js-scripts/map_tests.js
        cargo run --all-features --example js -- js-scripts/new_precedence.js
        cargo run --all-features --example js -- js-scripts/null_n_undefined.js
        cargo run --all-features --example js -- js-scripts/number_integration_test.js
        cargo run --all-features --example js -- js-scripts/numbers_n_strings.js
        cargo run --all-features --example js -- js-scripts/object_super_method_stack_overflow.js
        cargo run --all-features --example js -- js-scripts/object_tests_01.js
        cargo run --all-features --example js -- js-scripts/object_tests_02.js
        cargo run --all-features --example js -- js-scripts/object_tests_03.js
        cargo run --all-features --example js -- js-scripts/parameter_rest.js
        # cargo run --all-features --example js -- js-scripts/promise_tests.js
        cargo run --all-features --example js -- js-scripts/proper_dataview_test.js
        cargo run --all-features --example js -- js-scripts/regex_test_2.js
        cargo run --all-features --example js -- js-scripts/regex_test_3.js
        cargo run --all-features --example js -- js-scripts/regex_test_4.js
        cargo run --all-features --example js -- js-scripts/regex_test.js
        cargo run --all-features --example js -- js-scripts/set_tests_01.js
        cargo run --all-features --example js -- js-scripts/set_tests_02.js
        cargo run --all-features --example js -- js-scripts/set_tests_03.js
        # cargo run --all-features --example js -- js-scripts/set_time_out_tests.js
        cargo run --all-features --example js -- js-scripts/sharedarraybuffer_final.js
        cargo run --all-features --example js -- js-scripts/sharedarraybuffer_test.js
        cargo run --all-features --example js -- js-scripts/simple_dataview_test.js
        cargo run --all-features --example js -- js-scripts/template_string_tests_2.js
        cargo run --all-features --example js -- js-scripts/template_string_tests.js
        cargo run --all-features --example js -- js-scripts/test_array_join_split.js
        cargo run --all-features --example js -- js-scripts/test_dataview_js.js
        cargo run --all-features --example js -- js-scripts/try_catch_finally.js
        cargo run --all-features --example js -- js-scripts/typedarray_test_1.js
        cargo run --all-features --example js -- js-scripts/typeof_n_callable.js
        cargo run --all-features --example js -- js-scripts/weakmap_tests.js
        cargo run --all-features --example js -- js-scripts/weakset_tests.js

    - name: Abort on error
      if: ${{ failure() }}
      run: echo "Some of jobs failed" && false
